### PR TITLE
Welcome Message

### PR DESCRIPTION
**Pull request by paddatrapper**
Fixes the welcome message and IRC help issues in #54.

### CODE REVIEW

**Comment by paddatrapper** [comment]
OK there we go, critique away!

**Comment by paddatrapper** [comment]
@projectdelphai is this PR fine to be merged?

**Comment by projectdelphai** [comment]
Of course :D And considering how inactive I've been lately, don't hesitate to wait for me, I trust your guys' judgements.

**Comment by paddatrapper** [comment]
@projectdelphai neither of us have the rights to push to this repo

**Pull request merged**
